FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir mlflow==2.12.2
VOLUME ["/app/mlruns"]
CMD ["mlflow", "server", "--backend-store-uri", "file:/app/mlruns", "--default-artifact-root", "file:/app/mlruns", "--host", "0.0.0.0", "--port", "5000"]
