FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src ./src
COPY serving ./serving
COPY data/sample ./data/sample
ENV MLFLOW_TRACKING_URI="file:/app/mlruns"
CMD ["uvicorn", "serving.app:app", "--host", "0.0.0.0", "--port", "8000"]
